# ------------------------------------------------------------------------
# Swift-DETR
# Copyright (c) 2025 Roboflow. All Rights Reserved.
# Licensed under the Apache License, Version 2.0 [see LICENSE for details]
# ------------------------------------------------------------------------

"""LightningCLI entry point for Swift-DETR training and evaluation.

Provides the ``swiftdetr`` command with auto-generated subcommands::

    swiftdetr fit     --config configs/swiftdetr_small.yaml
    swiftdetr validate --ckpt_path output/best.ckpt
    swiftdetr test    --ckpt_path output/best.ckpt
    swiftdetr predict --ckpt_path output/best.ckpt

Both ``SwiftDetrModule`` and ``SwiftDetrDataModule`` share the same
``(model_config, train_config)`` constructor signature.  ``link_arguments``
eliminates the duplication so the user specifies each config group once;
the datamodule receives the same values automatically at parse time.
"""

from pytorch_lightning.cli import LightningArgumentParser, LightningCLI

from swiftdetr.training.module_data import SwiftDetrDataModule
from swiftdetr.training.module_model import SwiftDetrModule


class SwiftDetrCli(LightningCLI):
    """LightningCLI subclass for Swift-DETR training and evaluation.

    Wires ``SwiftDetrModule`` and ``SwiftDetrDataModule`` under a unified CLI,
    with argument linking that shares ``model_config`` and ``train_config``
    between module and datamodule so the user only specifies them once.

    Auto-generated subcommands: ``fit``, ``validate``, ``test``, ``predict``.
    """

    def add_arguments_to_parser(self, parser: LightningArgumentParser) -> None:
        """Register argument links that share configs between module and datamodule.

        Linking ``model.model_config`` → ``data.model_config`` and
        ``model.train_config`` → ``data.train_config`` means the user specifies
        both config groups once; the datamodule receives the same values
        automatically.

        Args:
            parser: The jsonargparse ``LightningArgumentParser`` provided by
                ``LightningCLI``.
        """
        parser.link_arguments("model.model_config", "data.model_config", apply_on="parse")
        parser.link_arguments("model.train_config", "data.train_config", apply_on="parse")


def main() -> None:
    """Entry point for the ``swiftdetr`` CLI.

    Constructs and runs ``SwiftDetrCli`` with ``SwiftDetrModule`` and
    ``SwiftDetrDataModule``.  Subcommands are auto-generated by
    ``LightningCLI``: ``fit``, ``validate``, ``test``, ``predict``.
    """
    SwiftDetrCli(SwiftDetrModule, SwiftDetrDataModule)


if __name__ == "__main__":
    main()
